# Generated by Django 3.2.4 on 2021-06-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaltable',
            options={'verbose_name_plural': '打卡记录'},
        ),
    ]
