# Generated by Django 3.2.4 on 2021-06-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_alter_generaltable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='name',
            options={'verbose_name_plural': '人员'},
        ),
    ]
