# Generated by Django 3.2.4 on 2021-06-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_alter_name_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_num', models.CharField(max_length=40, verbose_name='编号')),
                ('check_name', models.CharField(max_length=40, verbose_name='姓名')),
                ('check_date', models.DateField(verbose_name='日期')),
                ('check_morning', models.CharField(max_length=1, verbose_name='上午')),
                ('check_noon', models.CharField(max_length=1, null=True, verbose_name='中午')),
                ('check_afternoon', models.CharField(max_length=1, verbose_name='下午')),
                ('check_state', models.CharField(max_length=10, null=True, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '筛选记录',
            },
        ),
    ]
