# Generated by Django 3.2.4 on 2021-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_auxiliary_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaltable',
            name='user_name',
            field=models.CharField(max_length=40, null=True, verbose_name='姓名'),
        ),
    ]
