# Generated by Django 3.2.4 on 2021-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0006_generaltable_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascreen',
            name='check_explain',
            field=models.CharField(max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='auxiliary',
            name='auxiliary_sign',
            field=models.CharField(max_length=10, verbose_name='标记'),
        ),
        migrations.AlterField(
            model_name='auxiliary',
            name='auxiliary_type',
            field=models.CharField(max_length=10, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='datascreen',
            name='check_state',
            field=models.CharField(max_length=10, null=True, verbose_name='标记'),
        ),
    ]
