# Generated by Django 3.2.4 on 2021-06-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0008_remove_datascreen_check_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascreen',
            name='check_afternoon',
            field=models.IntegerField(verbose_name='下午'),
        ),
        migrations.AlterField(
            model_name='datascreen',
            name='check_morning',
            field=models.IntegerField(verbose_name='上午'),
        ),
        migrations.AlterField(
            model_name='datascreen',
            name='check_noon',
            field=models.IntegerField(null=True, verbose_name='中午'),
        ),
    ]
