# Generated by Django 3.2.4 on 2021-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0011_alter_datascreen_check_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='datascreen',
            name='check_day',
            field=models.IntegerField(null=True, verbose_name='请假天数'),
        ),
    ]
