# Generated by Django 3.2.4 on 2021-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0012_datascreen_check_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auxiliary',
        ),
        migrations.AlterModelOptions(
            name='datascreen',
            options={'verbose_name_plural': '汇总'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_time_interval',
            field=models.CharField(choices=[('上午', '上午'), ('中午', '中午'), ('下午', '下午'), ('全天', '全天')], max_length=10, verbose_name='时间段'),
        ),
    ]
