# Generated by Django 3.2.4 on 2021-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0013_auto_20210629_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('register_date', models.DateField(verbose_name='日期')),
                ('register_type', models.CharField(choices=[('事假', '事假'), ('病假', '病假'), ('丧假', '丧假'), ('婚假', '婚假')], max_length=10, verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '请假登记',
            },
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name_plural': '外出、报备登记'},
        ),
    ]
