# Generated by Django 3.2.4 on 2021-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0014_auto_20210629_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_day',
            field=models.IntegerField(null=True, verbose_name='请假天数'),
        ),
    ]
