# Generated by Django 3.2.4 on 2021-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0017_alter_datascreen_check_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='register_day',
            field=models.CharField(default=1, max_length=10, verbose_name='请假天数'),
        ),
    ]
