# Generated by Django 3.2.4 on 2021-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0018_alter_register_register_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='register_time',
            field=models.CharField(choices=[('上午', '上午'), ('下午', '下午'), ('全天', '全天')], default='全天', max_length=10, verbose_name='时间段'),
        ),
    ]
