# Generated by Django 3.2.4 on 2021-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0019_register_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascreen',
            name='check_state',
            field=models.CharField(max_length=10, null=True, verbose_name='请假类型'),
        ),
    ]
