# Generated by Django 3.2.4 on 2021-07-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0020_alter_datascreen_check_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascreen',
            name='check_afternoon',
            field=models.CharField(max_length=40, verbose_name='下午'),
        ),
        migrations.AlterField(
            model_name='datascreen',
            name='check_morning',
            field=models.CharField(max_length=40, verbose_name='上午'),
        ),
        migrations.AlterField(
            model_name='datascreen',
            name='check_noon',
            field=models.CharField(max_length=40, null=True, verbose_name='中午'),
        ),
    ]
